### ISSUE TITLE
Slack Contacts; Admin GUI does not close/hide

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-smart-contextual-assistance-app#14]
When adding Slack contacts, after login/authorisation, the Admin GUI does not close / hide

**Comment by tiagolb** [comment]
Fixed in https://github.com/reTHINK-project/dev-runtime-browser/pull/79
Once the pull request is accepted this issue can be closed

**Comment by tiagolb** [comment]
The pull request was accepted. This issue can be closed.
