### ISSUE TITLE
IMS enabled

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-smart-contextual-assistance-app#9]
Update the Connector Hyperty to support interoperability with IMS as supported by QBWRTC Hyperty

**Comment by pchainho** [comment]
Make it work with Mobile numbers: ask @dvilchez  / @antonroman 

Dependency on #8 to use a connectionProvider for each SIP/E.164  address (to be set at the URL attribute)

**Comment by luistduarte** [comment]
Done on develop branch after merge of [this](https://github.com/reTHINK-project/dev-hyperty/pull/61) pull request
